### ISSUE TITLE
Is this version going to support Rails 3.2?

### ISSUE THREAD

**Issue by heygambo** [turbolinks/turbolinks-rails#9]
Hey, thx for this awesome gem!
Is it meant to support Rails 3.2?

Bundling works but starting the rails server fails with this error: 

```
/Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:89:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'turbolinks'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `assets' for #<Rails::Engine::Configuration:0x007feb93786f50>
Backtrace for gem load error is:
/Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-3.2.22.2/lib/rails/railtie/configuration.rb:85:in `method_missing'
/Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/turbolinks-5.0.0.beta2/lib/turbolinks.rb:17:in `<class:Engine>'
/Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/turbolinks-5.0.0.beta2/lib/turbolinks.rb:14:in `<module:Turbolinks>'
/Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/turbolinks-5.0.0.beta2/lib/turbolinks.rb:5:in `<top (required)>'
/Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
/Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
/Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
/Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
/Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
/Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
/Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
/Users/gambo/Sites/Boxes/config/application.rb:13:in `<top (required)>'
/Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-3.2.22.2/lib/rails/commands.rb:53:in `require'
/Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-3.2.22.2/lib/rails/commands.rb:53:in `block in <top (required)>'
/Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-3.2.22.2/lib/rails/commands.rb:50:in `tap'
/Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-3.2.22.2/lib/rails/commands.rb:50:in `<top (required)>'
bin/rails:10:in `require'
bin/rails:10:in `<main>'
Bundler Error Backtrace:
    from /Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:85:in `block (2 levels) in require'
    from /Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
    from /Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
    from /Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
    from /Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
    from /Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
    from /Users/gambo/Sites/Boxes/config/application.rb:13:in `<top (required)>'
    from /Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-3.2.22.2/lib/rails/commands.rb:53:in `require'
    from /Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-3.2.22.2/lib/rails/commands.rb:53:in `block in <top (required)>'
    from /Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-3.2.22.2/lib/rails/commands.rb:50:in `tap'
    from /Users/gambo/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/railties-3.2.22.2/lib/rails/commands.rb:50:in `<top (required)>'
    from bin/rails:10:in `require'
    from bin/rails:10:in `<main>'
```

**Comment by maland** [comment]
+1

**Comment by webrails** [comment]
Having the same issue with Rails 3.2.17 and turbolinks 5.0.0. Any news?

**Comment by rafaelfranca** [comment]
Rails 3 is not supported anymore.

**Comment by dalecarter** [comment]
Hi There. I set these two gems in the Gemfile
  gem 'turbolinks', '~> 2.5', '>= 2.5.3'
  gem 'jquery-turbolinks'

and in application.js had this in place

//= require jquery
//= require jquery.turbolinks
//= require jquery_ujs
//= require jquery-ui
//= require bootstrap
//= require_tree .
//= require /lib/lazysizes.min.js
//= require turbolinks

and had to do a bundle update to remove the 5.0.0 version of turbolinks frm gemfile.lock.  Then it ran for me.

Hope that helps webrails

**Comment by dominicsayers** [comment]
For anyone else looking for historical versions: try https://github.com/turbolinks/turbolinks-classic

**Comment by jesperrojestal** [comment]
Shouldn't the gemspec specify that it doesn't support rails <= 4.0 or is it any particular reason rails isn't a dependency at all in the spec?
